{{- if .Values.api.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "macroshock.fullname" . }}-{{ .Values.api.name }}
  labels:
    {{- include "macroshock.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.api.name }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "macroshock.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.api.name }}
{{- end }}
