{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "macroshock.fullname" . }}
  labels:
    {{- include "macroshock.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          {{- if .Values.api.enabled }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "macroshock.fullname" . }}-{{ .Values.api.name }}
                port:
                  number: {{ .Values.api.service.port }}
          {{- end }}
          {{- if .Values.dashboard.enabled }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "macroshock.fullname" . }}-{{ .Values.dashboard.name }}
                port:
                  number: {{ .Values.dashboard.service.port }}
          {{- end }}
{{- end }}
